# Generated by Django 2.2.1 on 2019-05-04 08:04

from django.db import migrations
import project.football.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Football',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.sport',),
        ),
        migrations.CreateModel(
            name='FootballLeague',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(project.football.mixins.FootballSaveMixin, 'core.league'),
        ),
        migrations.CreateModel(
            name='FootballReferee',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(project.football.mixins.FootballSaveMixin, 'core.referee'),
        ),
        migrations.CreateModel(
            name='FootballSource',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(project.football.mixins.FootballSaveMixin, 'core.loadsource'),
        ),
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(project.football.mixins.FootballSaveMixin, 'core.team'),
        ),
    ]
