# Generated by Django 2.2.1 on 2019-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190505_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('F', 'Finished'), ('S', 'Scheduled'), ('C', 'Cancelled'), ('I', 'Interrupted')], default='S', max_length=5, verbose_name='Status'),
        ),
    ]
