# Generated by Django 2.2.1 on 2019-05-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190511_1637'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchreferee',
            name='unique_match_referee',
        ),
        migrations.AddConstraint(
            model_name='matchreferee',
            constraint=models.UniqueConstraint(fields=('match',), name='unique_match_referee'),
        ),
    ]
