# Generated by Django 2.2.1 on 2019-05-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    def set_handlers(apps, schema_editor):
        LoadSource = apps.get_model('core', 'LoadSource')
        LoadSource.objects.filter(slug='espn').update(source_handler='load.handlers.ESPNHandler')
        LoadSource.objects.filter(slug='football_data').update(source_handler='load.handlers.FootballDataHandler')
        LoadSource.objects.filter(slug='understat').update(source_handler='load.handlers.UnderstatHandler')
        LoadSource.objects.filter(slug='xscores').update(source_handler='load.handlers.XScoresHandler')
        LoadSource.objects.filter(slug='1xbet').update(source_handler='load.handlers.Football1XBetHandler')
        LoadSource.objects.filter(slug='parimatch').update(source_handler='load.handlers.FootballParimatchHandler')

    dependencies = [
        ('core', '0007_matchstats_load_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsource',
            name='error_limit',
            field=models.IntegerField(default=10, verbose_name='Error limit'),
        ),
        migrations.AddField(
            model_name='loadsource',
            name='max_odd',
            field=models.DecimalField(decimal_places=3, default=10, max_digits=10, verbose_name='Max odd'),
        ),
        migrations.AddField(
            model_name='loadsource',
            name='min_odd',
            field=models.DecimalField(decimal_places=3, default=1.1, max_digits=10, verbose_name='Min odd'),
        ),
        migrations.RunPython(set_handlers),
    ]
