# Generated by Django 2.2.1 on 2019-10-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190615_1700'),
    ]

    def addUnknownTeamType(apps, schema_editor):
        TeamType = apps.get_model('core', 'TeamType')
        team_type = TeamType(slug='unknown', name="Unknonwn")
        team_type.save()
        unknown_type_type = TeamType.objects.get(slug="unknown")
        #update League
        League = apps.get_model('core', 'League')
        League.objects.filter(team_type__isnull=True).update(team_type=unknown_type_type)
        #update Team
        Team = apps.get_model('core', 'Team')
        Team.objects.filter(team_type__isnull=True).update(team_type=unknown_type_type)



    operations = [
        migrations.RunPython(addUnknownTeamType),
    ]
