# Generated by Django 2.2.1 on 2019-07-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190615_1700'),
    ]

    def insertEmptyLoadSources(apps, schema_editor):
        Sport = apps.get_model('core', 'Sport')
        sport = Sport.objects.get(slug='football')
        LoadSource = apps.get_model('core', 'LoadSource')
        load_source = LoadSource(slug='na', 
                                 sport=sport,
                                 name='Unknown',
                                 reliability=1000,
                                 source_handler='',
                                 source_url='',
                                 is_loadable=False,
                                 is_betting=False
                                )
        load_source.save()

    operations = [
        migrations.RunPython(insertEmptyLoadSources),
    ]
