# Generated by Django 2.2.1 on 2019-10-12 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191012_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='team_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TeamType', verbose_name='Team type'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.TeamType', verbose_name='Team type'),
        ),
    ]
