# Generated by Django 2.2.1 on 2019-08-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_create_empty_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
