# Generated by Django 2.2.1 on 2019-11-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_create_empty_source'),
        ('core', '0012_foriegn_team_type'),
    ]

    operations = [
    ]
