# Generated by Django 2.2.1 on 2020-02-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20191124_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsource',
            name='load_days',
            field=models.IntegerField(default=10, verbose_name='Load days'),
        ),
    ]
