# Generated by Django 2.2.1 on 2020-01-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20191124_1401'),
        ('core', '0012_auto_20190806_1508'),
    ]

    operations = [
    ]
