# Generated by Django 2.2.1 on 2020-05-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20200106_2300'),
        ('core', '0015_auto_20200405_1717'),
    ]

    operations = [
    ]
