# Generated by Django 2.2.1 on 2022-02-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211210_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsource',
            name='saldo_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo'),
        ),
    ]
