# Generated by Django 2.2.1 on 2019-05-29 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_auto_20190529_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonHandler',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.loadsource',),
        ),
        migrations.CreateModel(
            name='SourceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End time')),
                ('status', models.CharField(choices=[('p', 'In process'), ('f', 'Finished'), ('e', 'Error'), ('i', 'Interrupted')], default='p', max_length=5, verbose_name='Status')),
                ('match_cnt', models.IntegerField(verbose_name='Match cnt')),
                ('err_cnt', models.IntegerField(verbose_name='Errors')),
                ('load_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LoadSource', verbose_name='Load source')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name='Last update')),
                ('load_date', models.DateField(blank=True, null=True, verbose_name='Load date')),
                ('league_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='League name')),
                ('match_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='League name')),
                ('load_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LoadSource', verbose_name='Load source')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Error text')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error message')),
                ('error_time', models.DateTimeField(blank=True, null=True, verbose_name='Error time')),
                ('league_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='League name')),
                ('match_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='League name')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='File name')),
                ('load_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LoadSource', verbose_name='Load source')),
                ('source_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load.SourceLog', verbose_name='Source log')),
            ],
        ),
        migrations.AddIndex(
            model_name='sourcelog',
            index=models.Index(fields=['load_source', 'status'], name='load_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sourcedetail',
            constraint=models.UniqueConstraint(fields=('load_source', 'slug'), name='unique_source_detail'),
        ),
    ]
