# Generated by Django 2.2.1 on 2019-05-30 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190529_1757'),
        ('load', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SourceLog',
            new_name='SourceSession',
        ),
        migrations.RemoveField(
            model_name='errorlog',
            name='source_log',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='source_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='load.SourceDetail', verbose_name='Load detail'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='load.SourceSession', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='sourcedetail',
            name='source_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='load.SourceSession', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='sourcedetail',
            name='status',
            field=models.CharField(choices=[('p', 'In process'), ('f', 'Finished')], default='p', max_length=5, verbose_name='Status'),
        ),
    ]
