# Generated by Django 2.2.1 on 2019-05-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0002_auto_20190530_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorlog',
            name='error_message',
        ),
        migrations.AddField(
            model_name='errorlog',
            name='error_context',
            field=models.TextField(blank=True, null=True, verbose_name='Context'),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='error_traceback',
            field=models.TextField(blank=True, null=True, verbose_name='Traceback'),
        ),
    ]
