# Generated by Django 2.2.1 on 2019-06-01 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('load', '0003_auto_20190531_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDetailLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(default='NA', max_length=100, verbose_name='Season')),
                ('league_name', models.CharField(max_length=100, verbose_name='League')),
                ('status', models.CharField(choices=[('p', 'In process'), ('f', 'Finished')], default='p', max_length=5, verbose_name='Status')),
                ('source_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load.SourceDetail', verbose_name='Detail')),
            ],
        ),
        migrations.CreateModel(
            name='SourceDetailMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(verbose_name='Match date')),
                ('match_name', models.CharField(max_length=100, verbose_name='Match')),
                ('status', models.CharField(choices=[('p', 'In process'), ('f', 'Finished')], default='p', max_length=5, verbose_name='Status')),
                ('source_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load.SourceDetail', verbose_name='Detail')),
                ('source_detail_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='load.SourceDetailLeague', verbose_name='Detail league')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sourcedetailmatch',
            constraint=models.UniqueConstraint(fields=('source_detail', 'match_date', 'match_name'), name='unique_source_detail_match'),
        ),
        migrations.AddConstraint(
            model_name='sourcedetailleague',
            constraint=models.UniqueConstraint(fields=('source_detail', 'season_name', 'league_name'), name='unique_source_detail_league'),
        ),
    ]
