# Generated by Django 2.2.1 on 2019-05-04 08:04

from django.db import migrations, models
import django.db.models.deletion
import project.betting.mixins


class Migration(migrations.Migration):

    initial = True


    def insertValueTypes(apps, schema_editor):
        ValueType = apps.get_model('betting', 'ValueType')
        ValueType.objects.create(slug='main', name='Main')
        ValueType.objects.create(slug='corner', name='Corners')
        ValueType.objects.create(slug='ycard', name='Yellow cards')
        ValueType.objects.create(slug='rcard', name='Red cards')
        ValueType.objects.create(slug='foul', name='Fouls')
        ValueType.objects.create(slug='shot-on-goal', name='Shots on goal')
        ValueType.objects.create(slug='shot', name='Shots')
        ValueType.objects.create(slug='offside', name='Offsides')
        ValueType.objects.create(slug='ball-possession', name='Ball possession')
        ValueType.objects.create(slug='penalty', name='Penalties')

    def insertBetTypes(apps, schema_editor):
        BetType = apps.get_model('betting', 'BetType')
        BetType.objects.create(slug='wdl', 
                               name='Match/period result',
                               description='Result of match or period.\nperiod=0,1,2\nteam=empty\nparam=w,d,l,wd,dl,wl',
                               handler='OddWDL'
                               )
        BetType.objects.create(slug='wdl_minute', 
                               name='Result for a given minute',
                               description='Result for a given minute.\nperiod=15,30,45,60,75,90\nteam=empty\nparam=w,d,l,wd,dl,wl',
                               handler='OddWDLMinute'
                               )

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Type')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('handler', models.CharField(blank=True, max_length=100, null=True, verbose_name='Handler')),
            ],
        ),
        migrations.CreateModel(
            name='ValueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='OddBookieConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Odd code')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Odd name')),
                ('period', models.IntegerField(blank=True, null=True, verbose_name='Period')),
                ('param', models.CharField(blank=True, max_length=255, verbose_name='Param')),
                ('team', models.CharField(blank=True, max_length=10, verbose_name='Team')),
                ('yes', models.CharField(max_length=1, verbose_name='Yes\\No')),
                ('bookie_handler', models.CharField(blank=True, max_length=100, verbose_name='Handler')),
                ('bet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.BetType', verbose_name='Bet type')),
                ('bookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LoadSource', verbose_name='Bookie')),
            ],
        ),
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(verbose_name='Period')),
                ('yes', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Yes\\No')),
                ('team', models.CharField(blank=True, choices=[('h', 'Home'), ('a', 'Away')], max_length=10, verbose_name='Team')),
                ('param', models.CharField(blank=True, max_length=255, verbose_name='Param')),
                ('odd_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Odd')),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('f', 'Finished'), ('c', 'Cancelled')], max_length=5, verbose_name='Status')),
                ('result', models.CharField(choices=[('n', 'Unknown'), ('s', 'Success'), ('sp', 'Part success'), ('r', 'Return'), ('fp', 'Part fail'), ('f', 'Fail')], max_length=5, verbose_name='Result')),
                ('result_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Result value')),
                ('odd_update', models.DateTimeField(blank=True, null=True, verbose_name='Odd update')),
                ('result_update', models.DateTimeField(blank=True, null=True, verbose_name='Result update')),
                ('bet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.BetType', verbose_name='Bet type')),
                ('bookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betting_odd_bookie_fk', to='core.LoadSource', verbose_name='Bookie')),
                ('load_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betting_odd_source_fk', to='core.LoadSource', verbose_name='Source')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Match', verbose_name='Match')),
                ('odd_bookie_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.OddBookieConfig', verbose_name='Bookie Odd')),
                ('value_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='betting.ValueType', verbose_name='Value type')),
            ],
        ),
        migrations.CreateModel(
            name='OddWDL',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.AddConstraint(
            model_name='oddbookieconfig',
            constraint=models.UniqueConstraint(fields=('bookie', 'code'), name='unique_odd_bookie_conf'),
        ),
        migrations.AddConstraint(
            model_name='odd',
            constraint=models.UniqueConstraint(fields=('match', 'bet_type', 'bookie', 'value_type', 'period', 'yes', 'team', 'param'), name='unique_odd'),
        ),
        migrations.RunPython(insertBetTypes),
        migrations.RunPython(insertValueTypes),
    ]
