# Generated by Django 2.2.1 on 2019-05-22 08:50

import betting.mixins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddWDLMinute',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
    ]
