# Generated by Django 2.2.1 on 2019-05-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    def insertBetTypes(apps, schema_editor):
        BetType = apps.get_model('betting', 'BetType')
        BetType.objects.create(slug='result_half1_full', 
                               name='Result HT-FT',
                               description='Result half time and full time of match.\nperiod=0\nteam=empty\nparam=(1,X,2)/(1,X,2)',
                               handler='OddResultHalf1Full'
                               )
        BetType.objects.create(slug='result_half1_half2', 
                               name='Result HT1-HT2',
                               description='Result the first half time and the second half time.\nperiod=0\nteam=empty\nparam=(1,X,2)/(1,X,2)',
                               handler='OddResultHalf1Half2'
                               )
        BetType.objects.create(slug='win_both', 
                               name='Win both halves',
                               description='Team will win in each half\nperiod=0\nteam=h,a,empty-any team\nparam=empty',
                               handler='OddWinBoth'
                               )
        BetType.objects.create(slug='win_least_one_half', 
                               name='Win any half',
                               description='Team will win in any half\nperiod=0\nteam=h,a\nparam=empty',
                               handler='OddWinLeastOneHalf'
                               )
        BetType.objects.create(slug='win_to_nil', 
                               name='Win to nil',
                               description='Team will win and not miss a goal\nperiod=0,1,2\nteam=h,a,empty-any team\nparam=empty',
                               handler='OddWinToNil'
                               )
        BetType.objects.create(slug='correct_score', 
                               name='Correct Score',
                               description='Correct score (or multiple scores) of match or half\nperiod=0,1,2\nteam=empty\nparam=1:2 or 1:1,1:2',
                               handler='OddCorrectScore'
                               )
        BetType.objects.create(slug='total_even_odd', 
                               name='Total Even/Odd',
                               description='Parity of goals (one team or both) scored in match or half\nperiod=0,1,2\nteam=h,a,empty-both\nparam=even,odd',
                               handler='OddTotalEvenOdd'
                               )
        BetType.objects.create(slug='total_over', 
                               name='Total Over',
                               description='Total of goals (one team or both, in match or half) greater than or equal to parameter\nperiod=0,1,2\nteam=h,a,empty-both\nparam=total value (example: 1 or 1.5 or 1.25)',
                               handler='OddTotalOver'
                               )
        BetType.objects.create(slug='total_under', 
                               name='Total Under',
                               description='Total of goals (one team or both, in match or half) less than or equal to parameter\nperiod=0,1,2\nteam=h,a,empty-both\nparam=total value (example: 1 or 1.5 or 1.25)',
                               handler='OddTotalUnder'
                               )
        BetType.objects.create(slug='total_both_halves_over', 
                               name='Total Both Halves Over',
                               description='Total of goals in both halves greate than parameter\nperiod=0\nteam=h,a,empty-both\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddTotalBothHalvesOver'
                               )
        BetType.objects.create(slug='total_both_halves_under', 
                               name='Total Both Halves Under',
                               description='Total of goals in both halves less than parameter\nperiod=0\nteam=h,a,empty-both\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddTotalBothHalvesUnder'
                               )
        BetType.objects.create(slug='total_over_minutes', 
                               name='Total Over 15-min intervals',
                               description='Total of goals (one team or both) scored in 15 minute interval greater than or equal to parameter\nperiod=15,30,45,60,75,90\nteam=h,a,empty-both\nparam=total value (example: 0.5 or 1 or 1.25)',
                               handler='OddTotalOverMinutes'
                               )
        BetType.objects.create(slug='total_under_minutes', 
                               name='Total Under 15-min intervals',
                               description='Total of goals (one team or both) scored in 15 minute interval greater than or equal to parameter\nperiod=15,30,45,60,75,90\nteam=h,a,empty-both\nparam=total value (example: 0.5 or 1 or 1.25)',
                               handler='OddTotalUnderMinutes'
                               )
        BetType.objects.create(slug='total', 
                               name='Exact total',
                               description='Exact total of goals (one team or both) scored in match, half or 15 minute interval\nperiod=0,1,2,15,30,45,60,75,90\nteam=h,a,empty-both\nparam=1 or 0,1,2',
                               handler='OddTotal'
                               )
        BetType.objects.create(slug='handicap', 
                               name='Handicap',
                               description='Handicap of goals in match or half\nperiod=0,1,2\nteam=h,a\nparam=0 or +1.5 or -1 or +1.75 or ...',
                               handler='OddHandicap'
                               )
        BetType.objects.create(slug='handicap_minutes', 
                               name='Handicap 15-min intervals',
                               description='Handicap of goals in 15 minute intervals\nperiod=15,30,45,60,75,90\nteam=h,a\nparam=0 or +1.5 or -1 or +1.75 or ...',
                               handler='OddHandicapMinutes'
                               )
        BetType.objects.create(slug='consecutive_goals', 
                               name='Consecutive Goals',
                               description='Team will score N consecutive goals\nperiod=0\nteam=h,a,empty-any\nparam=N (N>1, N consecutive goals)',
                               handler='OddConsecutiveGoals'
                               )
        BetType.objects.create(slug='itotal_both_over', 
                               name='Both total over',
                               description='Both team will score more than N goals in match or half\nperiod=0,1,2\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalBothOver'
                               )
        BetType.objects.create(slug='itotal_both_under', 
                               name='Both total under',
                               description='Both team will score less than N goals in match or half\nperiod=0,1,2\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalBothUnder'
                               )
        BetType.objects.create(slug='itotal_only_over', 
                               name='Only total over',
                               description='Only one team will score greater than N goals in match or half\nperiod=0,1,2\nteam=h,a,empty-any\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalOnlyOver'
                               )
        BetType.objects.create(slug='itotal_only_under', 
                               name='Only total under',
                               description='Only one team will score less than N goals in match or half\nperiod=0,1,2\nteam=h,a,empty-any\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalOnlyUnder'
                               )
        BetType.objects.create(slug='itotal_at_least_over', 
                               name='At least total over',
                               description='At least one team will score greater than N goals in match or half\nperiod=0,1,2\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalAtLeastOver'
                               )
        BetType.objects.create(slug='itotal_at_least_under', 
                               name='At least total under',
                               description='At least one team will score less than N goals in match or half\nperiod=0,1,2\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalAtLeastUnder'
                               )
        BetType.objects.create(slug='margin', 
                               name='Margin',
                               description='Team will win match or half in exactly N goals\nperiod=0,1,2\nteam=h,a,empty-any\nparam=list of integers (1 or 0,1 or 1,2,3 or ...)',
                               handler='OddMargin'
                               )
        BetType.objects.create(slug='w_and_total_over', 
                               name='Win & total over',
                               description='Team will win match or half and total greater than N goals\nperiod=0,1,2\nteam=h,a\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddWAndTotalOver'
                               )
        BetType.objects.create(slug='w_and_total_under', 
                               name='Win & total under',
                               description='Team will win match or half and total less than N goals\nperiod=0,1,2\nteam=h,a\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddWAndTotalUnder'
                               )
        BetType.objects.create(slug='wd_and_total_over', 
                               name='Win or draw & total over',
                               description='Team will win or draw in match or half and total greater than N goals\nperiod=0,1,2\nteam=h,a\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddWDAndTotalOver'
                               )
        BetType.objects.create(slug='wd_and_total_under', 
                               name='Win or draw & total under',
                               description='Team will win or draw in match or half and total less than N goals\nperiod=0,1,2\nteam=h,a\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddWDAndTotalUnder'
                               )
        BetType.objects.create(slug='both_to_score_and_total_over', 
                               name='Both score & total over',
                               description='Both team will score in match or half and total greater than N goals\nperiod=0,1,2\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddBothToScoreAndTotalOver'
                               )
        BetType.objects.create(slug='both_to_score_and_total_under', 
                               name='Both score & total under',
                               description='Both team will score in match or half and total less than N goals\nperiod=0,1,2\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddBothToScoreAndTotalUnder'
                               )
        BetType.objects.create(slug='not_both_to_score_and_total_over', 
                               name='At least one not score & total over',
                               description='At least one team will not score in match or half and total greater than N goals\nperiod=0,1,2\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddNotBothToScoreAndTotalOver'
                               )
        BetType.objects.create(slug='not_both_to_score_and_total_under', 
                               name='At least one not score & total under',
                               description='At least one team will not score in match or half and total less than N goals\nperiod=0,1,2\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddNotBothToScoreAndTotalUnder'
                               )
        BetType.objects.create(slug='wdl_and_both_teams_score', 
                               name='WDL & both score',
                               description='Win/draw/loose in match or half and both team will score\nperiod=0,1,2\nteam=empty\nparam=w,d,l,wd,dl,wl',
                               handler='OddWDLAndBothTeamsScore'
                               )
        BetType.objects.create(slug='both_to_score_at_1_2', 
                               name='Both score in 1 and 2 halves',
                               description='Detail both team to score in 1 and s halves (see parameters)\nperiod=0\nteam=empty\nparam=0/0,0/1,1/0 or 0/0',
                               handler='OddBothToScoreAt1_2'
                               )
        BetType.objects.create(slug='itotal_both_over_in_both_halves', 
                               name='Both score over in both halves',
                               description='Both team will score greater than N goals in both halves\nperiod=0\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalBothOverInBothHalves'
                               )
        BetType.objects.create(slug='itotal_both_under_in_both_halves', 
                               name='Both score under in both halves',
                               description='Both team will score less than N goals in both halves\nperiod=0\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalBothUnderInBothHalves'
                               )
        BetType.objects.create(slug='itotal_only_over_in_both_halves', 
                               name='Only one score over in both halves',
                               description='Only one team will score greater than N goals in both halves\nperiod=0\nteam=h,a,empty-neither\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalOnlyOverInBothHalves'
                               )
        BetType.objects.create(slug='itotal_only_under_in_both_halves', 
                               name='Only one score under in both halves',
                               description='Only one team will score less than N goals in both halves\nperiod=0\nteam=h,a\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalOnlyUnderInBothHalves'
                               )
        BetType.objects.create(slug='itotal_both_over_and_either_win', 
                               name='Both score & either win',
                               description='Both team will score and either win in match or half\nperiod=0,1,2\nteam=empty\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddITotalBothOverAndEitherWin'
                               )
        BetType.objects.create(slug='race_to_goals', 
                               name='Race to goals',
                               description='Who first score N goal in match or half\nperiod=0,1,2\nteam=h,a,empty-neither\nparam=integer (1,2,..)',
                               handler='OddRaceToGoals'
                               )
        BetType.objects.create(slug='half_to_score_first_goal', 
                               name='Half score first goal',
                               description='Half to score first goal (team or any team)\nperiod=0\nteam=h,a,empty-any\nparam=1,2 (half number)',
                               handler='OddHalfToScoreFirstGoal'
                               )
        BetType.objects.create(slug='time_to_score_first_goal', 
                               name='15-min interval score first goal',
                               description='15-minute interval to score first goal (team or any team)\nperiod=0\nteam=h,a,empty-any\nparam=15,30,45,60,75,90',
                               handler='OddTimeToScoreFirstGoal'
                               )
        BetType.objects.create(slug='draw_in_either_half', 
                               name='Draw in either half',
                               description='Draw in either half\nperiod=0\nteam=empty\nparam=empty',
                               handler='OddDrawInEitherHalf'
                               )
        BetType.objects.create(slug='highest_value_half', 
                               name='Highest value half',
                               description='In which half more goals scored (team or all teams)\nperiod=0\nteam=h,a,empty-all\nparam=1,X or 2',
                               handler='OddHighestValueHalf'
                               )
        BetType.objects.create(slug='win_no_bet', 
                               name='Win no bet',
                               description='No bet  wining of team in parameter "team". Param is result of the other team\nperiod=0,1,2\nteam=h,a\nparam=w or d',
                               handler='OddWinNoBet'
                               )
        # BetType.objects.create(slug='draw_least_one_half', 
        #                        name='Draw least one half',
        #                        description='Draw at least in one half\nperiod=0\nteam=empty\nparam=empty',
        #                        handler='OddDrawLeastOneHalf'
        #                        )
        BetType.objects.create(slug='w_and_itotal_over', 
                               name='Win & team total over',
                               description='Team will win (in match or half) and total goals greater than N (the same team) \nperiod=0,1,2\nteam=h,a\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddWAndITotalOver'
                               )
        BetType.objects.create(slug='w_and_itotal_under', 
                               name='Win & team total under',
                               description='Team will win (in match or half) and total goals less than N (the same team) \nperiod=0,1,2\nteam=h,a\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddWAndITotalUnder'
                               )
        BetType.objects.create(slug='wd_and_itotal_over', 
                               name='Win or draw & team total over',
                               description='Team will win or draw (in match or half) and total goals greater than N (the same team) \nperiod=0,1,2\nteam=h,a\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddWDAndITotalOver'
                               )
        BetType.objects.create(slug='wd_and_itotal_under', 
                               name='Win or draw & team total under',
                               description='Team will win or draw (in match or half) and total goals less than N (the same team) \nperiod=0,1,2\nteam=h,a\nparam=half-integer: 0.5,1.5,2.5,...',
                               handler='OddWDAndITotalUnder'
                               )
        BetType.objects.create(slug='w_and_total', 
                               name='Win & total',
                               description='Team will win and total goals of both team exacly equel N\nperiod=0,1,2\nteam=h,a\nparam=list of integers (1 or 0,1 or 1,2,3 or ...)',
                               handler='OddWAndTotal'
                               )
        # BetType.objects.create(slug='penalty_and_r_card', 
        #                        name='Penalty & r_card',
        #                        description='Penalty and red card (team or any team penalty + any team red card)\nperiod=0,1,2\nteam=h,a,empty-any\nparam=empty',
        #                        handler='OddPenaltyAndRCard'
        #                        )
        # BetType.objects.create(slug='penalty_or_r_card', 
        #                        name='Penalty or r_card',
        #                        description='Penalty or red card (team or any team penalty + any team red card)\nperiod=0,1,2\nteam=h,a,empty-any\nparam=empty',
        #                        handler='OddPenaltyOrRCard'
        #                        )
        # BetType.objects.create(slug='y_and_r_cards_over', 
        #                        name='yellow & red cards_over',
        #                        description='Number of cards greater than N (in match, half or 1-minute interval)\nperiod=0,1,2,15,30,45,60,75,90\nteam=h,a,empty-all\nparam=half-integer: 0.5,1.5,2.5,...',
        #                        handler='OddYAndRCardsOver'
        #                        )
        # BetType.objects.create(slug='y_and_r_cards_under', 
        #                        name='yellow & red cards_under',
        #                        description='Number of cards less than N (in match, half or 1-minute interval)\nperiod=0,1,2,15,30,45,60,75,90\nteam=h,a,empty-all\nparam=half-integer: 0.5,1.5,2.5,...',
        #                        handler='OddYAndRCardsUnder'
        #                        )


    dependencies = [
        ('betting', '0002_oddwdlminute'),
    ]

    operations = [
        migrations.CreateModel(
            name='OddBothToScoreAndTotalOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddBothToScoreAndTotalUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddBothToScoreAt1_2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddConsecutiveGoals',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddCorrectScore',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddDrawInEitherHalf',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddDrawLeastOneHalf',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddHalfToScoreFirstGoal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddHandicap',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddHandicapMinutes',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddHighestValueHalf',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalAtLeastOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalAtLeastUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalBothOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalBothOverAndEitherWin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalBothOverInBothHalves',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalBothUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalBothUnderInBothHalves',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalOnlyOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalOnlyOverInBothHalves',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalOnlyUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddITotalOnlyUnderInBothHalves',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddMargin',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddNotBothToScoreAndTotalOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddNotBothToScoreAndTotalUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddPenaltyAndRCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddPenaltyOrRCard',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddRaceToGoals',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddResultHalf1Full',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddResultHalf1Half2',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddTimeToScoreFirstGoal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddTotal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddTotalBothHalvesOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddTotalBothHalvesUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddTotalEvenOdd',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddTotalOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddTotalOverMinutes',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddTotalUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddTotalUnderMinutes',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWAndITotalOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWAndITotalUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWAndTotal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWAndTotalOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWAndTotalUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWDAndITotalOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWDAndITotalUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWDAndTotalOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWDAndTotalUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWDLAndBothTeamsScore',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWinBoth',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWinLeastOneHalf',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWinNoBet',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddWinToNil',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddYAndRCardsOver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.CreateModel(
            name='OddYAndRCardsUnder',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.odd',),
        ),
        migrations.RunPython(insertBetTypes),
    ]
