# Generated by Django 2.2.1 on 2019-10-12 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_ceate_proxy_odd_models'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OddDrawLeastOneHalf',
        ),
        migrations.DeleteModel(
            name='OddPenaltyAndRCard',
        ),
        migrations.DeleteModel(
            name='OddPenaltyOrRCard',
        ),
        migrations.DeleteModel(
            name='OddYAndRCardsOver',
        ),
        migrations.DeleteModel(
            name='OddYAndRCardsUnder',
        ),
    ]
