# Generated by Django 2.2.1 on 2019-08-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_create_parimatch_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OddDrawLeastOneHalf',
        ),
        migrations.DeleteModel(
            name='OddPenaltyAndRCard',
        ),
        migrations.DeleteModel(
            name='OddPenaltyOrRCard',
        ),
        migrations.DeleteModel(
            name='OddYAndRCardsOver',
        ),
        migrations.DeleteModel(
            name='OddYAndRCardsUnder',
        ),
    ]
