# Generated by Django 2.2.1 on 2020-01-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_recreate_parimatch_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oddbookieconfig',
            name='bet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='betting.BetType', verbose_name='Bet type'),
        ),
    ]
