# Generated by Django 2.2.1 on 2020-05-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_recreate_parimatch_config'),
    ]

    operations = [
        migrations.RunSQL("""
BEGIN;
CREATE OR REPLACE VIEW synene.v_odd
AS
SELECT o.id, o.period, o.yes, o.team, o.param, o.odd_value, o.status, o.result, o.result_value, o.odd_update, o.result_update,
       o.bet_type_id, bt.name AS bet_type_name, bt.handler AS bet_type_handler, bt.description AS bet_type_description,
       o.bookie_id, boo.name AS bookie_name,
       o.odd_bookie_config_id, bc.code AS odd_bookie_config_code, bc.name AS odd_bookie_config_name,
       o.value_type_id, vt.name AS value_type_name, 
       o.load_source_id, ls.name AS load_source_name,
       o.match_id, th.name || ' - ' || ta.name AS match_name, m.match_date, m.result AS match_result, m.score,
       m.league_id, l.name AS league_name,
       l.country_id, c.code AS country_code, c.name AS country_name,
       m.team_h_id, th.name AS team_h_name,
       m.team_a_id, ta.name AS team_a_name
  FROM synene.betting_odd o 
  JOIN synene.core_match m ON(o.match_id = m.id)
  JOIN synene.core_team th ON(m.team_h_id = th.id)
  JOIN synene.core_team ta ON(m.team_a_id = ta.id)
  JOIN synene.core_league l ON(m.league_id = l.id)
  JOIN synene.core_country c ON(l.country_id = c.id)
  JOIN synene.betting_bettype bt ON(o.bet_type_id = bt.id)
  JOIN synene.core_loadsource boo ON(o.bookie_id = boo.id)
  LEFT JOIN synene.betting_oddbookieconfig bc ON(o.odd_bookie_config_id = bc.id)
  JOIN synene.betting_valuetype vt ON(o.value_type_id = vt.id)
  LEFT JOIN synene.core_loadsource ls ON(o.load_source_id = ls.id)
;
GRANT SELECT ON synene.v_odd TO PUBLIC;
COMMIT;
            """)
    ]
