# Generated by Django 2.2.1 on 2020-05-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0008_create_view_v_odd'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOdd',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='pk')),
                ('period', models.IntegerField(verbose_name='Period')),
                ('yes', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, verbose_name='Yes\\No')),
                ('team', models.CharField(blank=True, choices=[('h', 'Home'), ('a', 'Away')], max_length=10, verbose_name='Team')),
                ('param', models.CharField(blank=True, max_length=255, verbose_name='Param')),
                ('odd_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Odd')),
                ('status', models.CharField(choices=[('w', 'Waiting'), ('f', 'Finished'), ('c', 'Cancelled')], max_length=5, verbose_name='Status')),
                ('result', models.CharField(choices=[('n', 'Unknown'), ('s', 'Success'), ('sp', 'Part success'), ('r', 'Return'), ('fp', 'Part fail'), ('f', 'Fail')], max_length=5, verbose_name='Result')),
                ('result_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Result value')),
                ('odd_update', models.DateTimeField(blank=True, null=True, verbose_name='Odd update')),
                ('result_update', models.DateTimeField(blank=True, null=True, verbose_name='Result update')),
                ('bet_type_id', models.IntegerField(verbose_name='Bet type')),
                ('bet_type_name', models.CharField(max_length=100, verbose_name='Bet type name')),
                ('bet_type_description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Bet type description')),
                ('bet_type_handler', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bet type handler')),
                ('bookie_id', models.IntegerField(verbose_name='Bookie')),
                ('bookie_name', models.CharField(max_length=100, verbose_name='Bookie name')),
                ('odd_bookie_config_id', models.IntegerField(verbose_name='Bookie Odd')),
                ('odd_bookie_config_code', models.CharField(max_length=100, verbose_name='Bookie odd code')),
                ('odd_bookie_config_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bookie odd name')),
                ('value_type_id', models.IntegerField(verbose_name='Value type')),
                ('value_type_name', models.CharField(max_length=100, verbose_name='Value type name')),
                ('load_source_id', models.IntegerField(verbose_name='Source')),
                ('load_source_name', models.CharField(max_length=100, verbose_name='Load source name')),
                ('match_id', models.IntegerField(verbose_name='Match')),
                ('match_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Match name')),
                ('match_date', models.DateField(verbose_name='Match date')),
                ('match_result', models.CharField(blank=True, choices=[('w', 'Win'), ('d', 'Draw'), ('l', 'Loose')], max_length=5, null=True, verbose_name='Match result')),
                ('score', models.CharField(blank=True, max_length=100, null=True, verbose_name='Score')),
                ('league_id', models.IntegerField(verbose_name='League')),
                ('league_name', models.CharField(max_length=100, verbose_name='League name')),
                ('country_id', models.IntegerField(verbose_name='Country')),
                ('country_code', models.CharField(max_length=100, verbose_name='Country Code')),
                ('country_name', models.CharField(max_length=100, verbose_name='Country Name')),
                ('team_h_id', models.IntegerField(verbose_name='Home team')),
                ('team_h_name', models.CharField(max_length=100, verbose_name='Home Team Name')),
                ('team_a_id', models.IntegerField(verbose_name='Away team')),
                ('team_a_name', models.CharField(max_length=100, verbose_name='Away Team Name')),
            ],
            options={
                'db_table': 'v_odd',
                'managed': False,
            },
        ),
    ]
