# Generated by Django 2.2.1 on 2021-12-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0009_vodd'),
        ('betting', '0009_create_1xbet_config'),
    ]

    operations = [
    ]
