# Generated by Django 2.2.1 on 2021-12-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0012_predictorstandardpoisson'),
    ]

    def delete_team_skill_data(apps, schema_editor):

        TeamSkill = apps.get_model('betting', 'TeamSkill')
        TeamSkill.objects.all().delete()


    operations = [
        migrations.RemoveConstraint(
            model_name='teamskill',
            name='unique_team_skill_harvest',
        ),

        migrations.RunPython(delete_team_skill_data),
        
    ]
