# Generated by Django 2.2.1 on 2021-12-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0013_auto_20211228_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamskill',
            name='param',
            field=models.CharField(default='0', max_length=20, verbose_name='Param'),
        ),
        migrations.AddConstraint(
            model_name='teamskill',
            constraint=models.UniqueConstraint(fields=('harvest', 'team', 'param', 'event_date', 'match'), name='unique_team_skill_harvest'),
        ),
    ]
