# Generated by Django 2.2.1 on 2021-12-29 16:40

from datetime import datetime, date, timedelta

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0014_auto_20211228_0901'),
    ]


    def init_distribution(apps, schema_editor):

        Distribution = apps.get_model('betting', 'Distribution')

        distribution = Distribution.objects.create(
                                            slug = "xg-gathering",
                                            name = "xG distribution",
                                            gathering_handler = "xGGathering",
                                            start_date = date(2015, 1, 1),
                                            end_date = date(2020, 1, 1),
                                            interpolation = True,
                                            step = 0.2
                                            )

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('comment', models.CharField(blank=True, max_length=2000, verbose_name='Comment')),
                ('gathering_handler', models.CharField(blank=True, max_length=255, verbose_name='Gathering handler')),
                ('gathering_date', models.DateTimeField(blank=True, null=True, verbose_name='Gathering date')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('interpolation', models.BooleanField(verbose_name='Interpolation')),
                ('step', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Step')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param', models.CharField(default='0', max_length=20, verbose_name='Param')),
                ('object_id', models.IntegerField(default=0, verbose_name='Object ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Step')),
                ('result_value', models.IntegerField(default=0, verbose_name='Result value')),
                ('data', models.FloatField(verbose_name='Data')),
                ('ditribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Distribution', verbose_name='Distribution')),
            ],
        ),
        migrations.CreateModel(
            name='xGGathering',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.distribution',),
        ),
        migrations.AddConstraint(
            model_name='distributiondata',
            constraint=models.UniqueConstraint(fields=('ditribution', 'param', 'object_id', 'value', 'result_value'), name='unique_distribution_data'),
        ),

        migrations.RunPython(init_distribution),

    ]
