# Generated by Django 2.2.1 on 2022-02-01 09:12

from django.db import migrations
import project.betting.predictor_mixins


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0015_auto_20211229_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictorDistributionXG',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(project.betting.predictor_mixins.OriginalDataExtraction, project.betting.predictor_mixins.FixedDistributionForecasting, 'betting.predictor'),
        ),
        migrations.CreateModel(
            name='PredictorOrigDistrXG',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(project.betting.predictor_mixins.OriginalDataExtraction, project.betting.predictor_mixins.FixedDistributionForecastingEx, 'betting.predictor'),
        ),
        migrations.CreateModel(
            name='PredictorStdDistribH_XG_0',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(project.betting.predictor_mixins.StandartExtraction, project.betting.predictor_mixins.FixedDistributionForecasting, 'betting.predictor'),
        ),
        migrations.CreateModel(
            name='PredictorStdDistrXG',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(project.betting.predictor_mixins.StandartExtraction, project.betting.predictor_mixins.FixedDistributionForecastingEx, 'betting.predictor'),
        ),
        migrations.CreateModel(
            name='xGGatheringHStd0',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.distribution',),
        ),
    ]
