# Generated by Django 2.2.1 on 2022-02-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20211210_1604'),
        ('betting', '0016_predictordistributionxg_predictororigdistrxg_predictorstddistribh_xg_0_predictorstddistrxg_xggatheri'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSkillSandbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(verbose_name='Event date')),
                ('match_cnt', models.IntegerField(verbose_name='Match Count')),
                ('lvalue1', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('lvalue2', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('lvalue3', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('lvalue4', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('lvalue5', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('lvalue6', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('lvalue7', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('lvalue8', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('lvalue9', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('lvalue10', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value1', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value2', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value3', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value4', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value5', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value6', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value7', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value8', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value9', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('value10', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='LValue1')),
                ('param', models.CharField(default='0', max_length=20, verbose_name='Param')),
                ('forecast_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.ForecastSet', verbose_name='Forecast set')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Harvest', verbose_name='Harvest')),
                ('harvest_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.HarvestGroup', verbose_name='Harvest Group')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Match', verbose_name='Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team', verbose_name='Team')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastSandbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(blank=True, null=True, verbose_name='Match date')),
                ('success_chance', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Success chance')),
                ('lose_chance', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Lose chance')),
                ('result_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Result value')),
                ('kelly', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='kelly')),
                ('forecast_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.ForecastSet', verbose_name='Forecast set')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Harvest', verbose_name='Harvest')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Match', verbose_name='Match')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Odd', verbose_name='Odd')),
                ('predictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Predictor', verbose_name='Predictor')),
            ],
        ),
        migrations.AddIndex(
            model_name='teamskillsandbox',
            index=models.Index(fields=['forecast_set', 'harvest_group', 'event_date'], name='tskill_snd_hgrp_edate_idx'),
        ),
        migrations.AddConstraint(
            model_name='teamskillsandbox',
            constraint=models.UniqueConstraint(fields=('forecast_set', 'harvest', 'team', 'param', 'event_date', 'match'), name='unique_teamskill_sandbox'),
        ),
        migrations.AddConstraint(
            model_name='forecastsandbox',
            constraint=models.UniqueConstraint(fields=('forecast_set', 'match', 'odd', 'predictor'), name='unique_forecast_sandbox'),
        ),
    ]
