# Generated by Django 2.2.1 on 2022-02-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0017_auto_20220201_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed0',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamskillsandbox',
            name='changed9',
            field=models.BooleanField(default=False),
        ),
    ]
