# Generated by Django 2.2.1 on 2022-02-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0018_auto_20220209_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamskillsandbox',
            old_name='changed0',
            new_name='changed10',
        ),
    ]
