# Generated by Django 2.2.1 on 2022-02-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0019_auto_20220209_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='status',
            field=models.CharField(choices=[('s', 'Settled'), ('u', 'Unsettled')], default='u', max_length=5, verbose_name='Status'),
        ),
    ]
