# Generated by Django 2.2.1 on 2022-02-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_loadsource_saldo_amt'),
        ('betting', '0020_forecast_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Bet name')),
                ('status', models.CharField(choices=[('s', 'Settled'), ('u', 'Unsettled'), ('b', 'Bid'), ('f', 'Finished')], default='u', max_length=5, verbose_name='Status')),
                ('result', models.CharField(choices=[('n', 'Unknown'), ('s', 'Success'), ('sp', 'Part success'), ('r', 'Return'), ('fp', 'Part fail'), ('f', 'Fail')], max_length=5, verbose_name='Result')),
                ('betting_type', models.CharField(choices=[('s', 'Settled'), ('u', 'Unsettled')], max_length=5, verbose_name='Betting type')),
                ('odd_cnt', models.IntegerField(default=0, verbose_name='Odd cnt')),
                ('ins_time', models.DateTimeField(verbose_name='Ins time')),
                ('bid_time', models.DateTimeField(null=True, verbose_name='Bid time')),
                ('settled_time', models.DateTimeField(null=True, verbose_name='Settled time')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='Finish time')),
                ('min_date', models.DateField(null=True, verbose_name='Min odd date')),
                ('max_date', models.DateField(null=True, verbose_name='Max odd date')),
                ('success_chance', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Success chance')),
                ('lose_chance', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Lose chance')),
                ('odd_value', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Odd value')),
                ('expect_value', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Expect value')),
                ('kelly', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Kelly')),
                ('bet_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Bet amt')),
                ('result_value', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Result value')),
                ('win_amt', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Win amt')),
            ],
        ),
        migrations.AddField(
            model_name='odd',
            name='selected',
            field=models.CharField(blank=True, choices=[('u', 'Unselected'), ('s', 'Selected'), ('b', 'Bid')], max_length=5, null=True, verbose_name='Selected'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(choices=[('i', 'In'), ('o', 'Out'), ('c', 'Correct`'), ('b', 'Bid'), ('w', 'Win')], max_length=5, verbose_name='Type')),
                ('trans_date', models.DateField(verbose_name='Transaction date')),
                ('ins_time', models.DateTimeField(verbose_name='Ins time')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('comment', models.CharField(blank=True, choices=[('i', 'In'), ('o', 'Out'), ('c', 'Correct`'), ('b', 'Bid'), ('w', 'Win')], max_length=2000, verbose_name='Comment')),
                ('bookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LoadSource', verbose_name='Bookie')),
            ],
        ),
        migrations.CreateModel(
            name='SelectedOdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(blank=True, null=True, verbose_name='Match date')),
                ('success_chance', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Success chance')),
                ('lose_chance', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Lose chance')),
                ('result_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Result value')),
                ('kelly', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Kelly')),
                ('forecast_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.ForecastSet', verbose_name='Forecast set')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Harvest', verbose_name='Harvest')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Match', verbose_name='Match')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Odd', verbose_name='Odd')),
                ('predictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Predictor', verbose_name='Predictor')),
            ],
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_date', models.DateField(verbose_name='Saldo date')),
                ('saldo_amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo')),
                ('in_amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='In')),
                ('out_amt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Out')),
                ('bookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LoadSource', verbose_name='Bookie')),
            ],
        ),
        migrations.CreateModel(
            name='BetOdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('s', 'Settled'), ('u', 'Unsettled'), ('f', 'Finished')], default='u', max_length=5, verbose_name='Status')),
                ('result', models.CharField(choices=[('n', 'Unknown'), ('s', 'Success'), ('sp', 'Part success'), ('r', 'Return'), ('fp', 'Part fail'), ('f', 'Fail')], max_length=5, verbose_name='Result')),
                ('ins_time', models.DateTimeField(verbose_name='Ins time')),
                ('settled_time', models.DateTimeField(null=True, verbose_name='Settled time')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='Finish time')),
                ('match_date', models.DateField(blank=True, null=True, verbose_name='Match date')),
                ('success_chance', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Success chance')),
                ('lose_chance', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Lose chance')),
                ('odd_value', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Odd value')),
                ('expect_value', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Expect value')),
                ('kelly', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Kelly')),
                ('result_value', models.DecimalField(decimal_places=3, max_digits=10, null=True, verbose_name='Result value')),
                ('bet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='betting.Bet', verbose_name='Bet')),
                ('bookie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LoadSource', verbose_name='Bookie')),
                ('harvest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.Harvest', verbose_name='Harvest')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Match', verbose_name='Match')),
                ('odd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.Odd', verbose_name='Odd')),
                ('predictor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.Predictor', verbose_name='Predictor')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betting_bet_bet_trans_fk', to='betting.Transaction', verbose_name='Bet trans'),
        ),
        migrations.AddField(
            model_name='bet',
            name='bookie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.LoadSource', verbose_name='Bookie'),
        ),
        migrations.AddField(
            model_name='bet',
            name='win_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='betting_bet_win_trans_fk', to='betting.Transaction', verbose_name='Win trans'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['trans_date'], name='transaction_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='selectedodd',
            constraint=models.UniqueConstraint(fields=('forecast_set', 'odd'), name='unique_selected_odd'),
        ),
        migrations.AddConstraint(
            model_name='saldo',
            constraint=models.UniqueConstraint(fields=('bookie', 'saldo_date'), name='unique_saldo'),
        ),
        migrations.AddIndex(
            model_name='betodd',
            index=models.Index(fields=['match_date'], name='betodd_match_date_idx'),
        ),
        migrations.AddIndex(
            model_name='betodd',
            index=models.Index(fields=['ins_time'], name='betodd_ins_time_idx'),
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['ins_time'], name='bet_ins_time_idx'),
        ),
    ]
