# Generated by Django 2.2.1 on 2022-04-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0021_auto_20220220_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='xGGatheringCopy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.distribution',),
        ),
        migrations.CreateModel(
            name='xGGatheringHStd0Copy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('betting.distribution',),
        ),
        migrations.AddField(
            model_name='saldo',
            name='unsettled_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Unsettled amt'),
        ),
        migrations.AddField(
            model_name='saldo',
            name='unsettled_cnt',
            field=models.IntegerField(default=0, verbose_name='Unsettled cnt'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='betting_type',
            field=models.CharField(choices=[('s', 'Single'), ('e', 'Express')], max_length=5, verbose_name='Betting type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Comment'),
        ),
    ]
