# Generated by Django 2.2.1 on 2022-06-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220422_1121'),
        ('betting', '0022_auto_20220422_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='best_bet_type',
            field=models.IntegerField(null=True, verbose_name='Best Bet Type'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='best_odd',
            field=models.IntegerField(null=True, verbose_name='Best Odd'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='growth',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='growth'),
        ),
        migrations.AddField(
            model_name='forecast',
            name='odd_level',
            field=models.IntegerField(null=True, verbose_name='Odd Level'),
        ),
        migrations.AddField(
            model_name='forecastsandbox',
            name='best_bet_type',
            field=models.IntegerField(null=True, verbose_name='Best Bet Type'),
        ),
        migrations.AddField(
            model_name='forecastsandbox',
            name='best_odd',
            field=models.IntegerField(null=True, verbose_name='Best Odd'),
        ),
        migrations.AddField(
            model_name='forecastsandbox',
            name='growth',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='growth'),
        ),
        migrations.AddField(
            model_name='forecastsandbox',
            name='odd_level',
            field=models.IntegerField(null=True, verbose_name='Odd Level'),
        ),
        migrations.CreateModel(
            name='ForecastTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateField(blank=True, null=True, verbose_name='Match date')),
                ('success_chance', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Success chance')),
                ('lose_chance', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Lose chance')),
                ('result_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Result value')),
                ('kelly', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='kelly')),
                ('status', models.CharField(default='u', max_length=5, verbose_name='Status')),
                ('growth', models.DecimalField(decimal_places=6, max_digits=10, null=True, verbose_name='growth')),
                ('odd_level', models.IntegerField(null=True, verbose_name='Odd Level')),
                ('bet_type_slug', models.CharField(max_length=100, verbose_name='Bet_Type Slug')),
                ('period', models.IntegerField(verbose_name='Period')),
                ('yes', models.CharField(max_length=1, verbose_name='Yes\\No')),
                ('team', models.CharField(blank=True, max_length=10, verbose_name='Team')),
                ('param', models.CharField(blank=True, max_length=255, verbose_name='Param')),
                ('odd_value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Odd')),
                ('forecast_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.ForecastSet', verbose_name='Forecast set')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Harvest', verbose_name='Harvest')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Match', verbose_name='Match')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Odd', verbose_name='Odd')),
                ('predictor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Predictor', verbose_name='Predictor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='forecasttemp',
            constraint=models.UniqueConstraint(fields=('forecast_set', 'match', 'odd', 'predictor'), name='unique_forecasttest'),
        ),
    ]
